### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by divanski** [goliasz/pio-template-text-similarity#1]
after "pio train" command I get this error:

Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: The vocabulary size should be > 0

**Comment by goliasz** [comment]
What parameters do you set in engine.json for algorithm? What is your "minCount" value?

**Comment by goliasz** [comment]
This message comes from Word2Vec model in a situation when "minCount" is to high for a training data. It is because tokens with count lower than "minCount" are not taken into dictionary. Closing the issue.

**Comment by divanski** [comment]
This is default value:
"algorithms": [
    {
      "name": "tsimilarity",
      "params": {
        "seed" : 75,
        "minCount": 1,
        "learningRate": 0.025,
        "numIterations": 1,
        "vectorSize": 100,
        "minTokenSize": 3,
        "showText": true,
        "showDesc": false,
        "useExtTrainWords": true,
        "storeClearText": false
      }
    }
  ]

what is the correct settings for  engine.json?

**Comment by goliasz** [comment]
ok... So you have used default value, right? If yes the next question is what data have you used to train the engine? Demo data or your own set?

**Comment by divanski** [comment]
demo data

**Comment by goliasz** [comment]
what version of PIO and Spark are you using?

**Comment by divanski** [comment]
pio - versrion 0.9.5 

anyway... I will try everything from scratch
