### ISSUE TITLE
Id with Match Text 

### ISSUE THREAD

**Issue by dipenpatel235** [goliasz/pio-template-text-similarity#3]
Hello...
I Have Implement below api but i get id no. of match text but i want whole match sentence on that ID.
SO how i get that ?

 curl -X POST -H "Content-Type: application/json" -d '{"doc": "DJs flock by when MTV ax quiz prog. Five quacking zephyrs jolt my wax bed.", "limit", 3}' http://localhost:8000/queries.json

{"docScores":[{"score":0.0,"id":"8","similarText":"","textDesc":""},{"score":0.0,"id":"14","similarText":"","textDesc":""},{"score":0.0,"id":"7","similarText":"","textDesc":""}]}

Thanks

**Comment by goliasz** [comment]
Hi,

Try to use following values in your engine.json file:
"showText": true,
"showDesc": true,
"storeClearText": true

Hope this helps.
